// Class automatically generated by Dev-C++ New Class wizard

#ifndef ECON_H
#define ECON_H
#include <string>

using namespace std;

/*
 * No description
 */
class econ
{
	public:
		// class constructor
		econ();
		void infl();
		void gdp();
		void consume();
		void help();

		// class destructor
		~econ();
};

#endif // ECON_H
