// Class automatically generated by Dev-C++ New Class wizard

#ifndef ELECT_H
#define ELECT_H

/*
 * No description
 */
class elect
{
	public:
		// class constructor
		elect();
    		void horse();
    		void kilo();
    		void kiloAm();
    		void imped();
    		void rescolor();
		void oscillators();
		void impedan();
		void npnamp();
    		
                void clear();
    		void calc();
    		void help();
		// class destructor
		~elect();
};

#endif // ELECT_H
