// Class automatically generated by Dev-C++ New Class wizard

#ifndef MATH_H
#define MATH_H
#include <string>

using namespace std;

/*
 * No description
 */
class math
{
	private:
		double factoreal(int n){
			double ret =n;
			for(int i=(n-1); i> 0; i--)
				ret *= i;

			return ret;
		}
	public:
		// class constructor
		math();
		void dotprod();
		void magnetud();
		void cross();
		void sine();
		void calcplane();
		void coss();
		void tang();
		void shape();
		void shadow();
		void sanDev();
		void groth();
		void rando();
		void clear();
		void prob();
		void dataAnal();
		void MatrixCalc();
		void calc();
		void help();

		// class destructor
		~math();
};

#endif // MATH_H
