// Class automatically generated by Dev-C++ New Class wizard

#ifndef VIPER_H
#define VIPER_H
#include <string>

using namespace std;
/*
 * No description
 */
class viper
{
	public:
		// class constructor
		viper();
		public:
               
               void calo();
               void consaccel();
               void consenergy();
               void kenenergy();
               void projectile();
               void torque();
               void spring();
               void resistor();
               void grav();
               void momentum();
               void cent();
               void thermexp();
               void heatcap();
               void graven(); 
               void adiabetic();
               void elecField();
               void componet();
               void magnet();
               void ior();
               void lens();
               void light();
               void wave();
               void rad();
               void atomic();
	       void fluidMec();
               
               void help();
               void calc();
               void clear();
		// class destructor
		~viper();
};

#endif // VIPER_H
